#!/usr/bin/python3
import random
import string

pass_length = 10

def pass_generator():
    password = ''
    for i in range(pass_length):
        password += random.choice(string.digits + string.ascii_letters + string.punctuation)
    return password

print (pass_generator())
