#!/usr/bin/python3
import random
import string

pass_length = 10

def pass_generator(length = 8):
    return ''.join(random.choice(string.ascii_letters + string.digits + string.punctuation) for _ in range(length))

print (pass_generator())
